name: DuckDB Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone DuckDB repository
        run: |
          git clone https://github.com/duckdb/duckdb-web.git duckdb

      - name: Remove non relevant directories
        run: |
          rm -rf duckdb/docs/archive
          rm -rf duckdb/docs/sql/tutorial

      - name: Create docs directory
        run: mkdir -p docs/duckdb

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Docs to prompt
        run: uvx files-to-prompt -e md duckdb/docs/ | uvx strip-tags -m > docs/duckdb/docs.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git commit -m "Update DuckDB documentation" || echo "No changes to commit"
          git push
