name: Polars Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone Polars repository
        run: |
          git clone https://github.com/pola-rs/polars.git polars

      - name: Create docs directory
        run: mkdir -p docs/polars

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Docs to prompt
        run: uvx files-to-prompt -e md polars/docs/source/ | uvx strip-tags -m > docs/polars/docs.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git commit -m "Update Polars documentation" || echo "No changes to commit"
          git push
